language: cpp

dist: trusty
sudo: required

compiler:
  - clang
  - gcc

env:
  - BUILD=Release
  - BUILD=RelWithDebInfo
  - BUILD=Debug

addons:
  apt:
    packages:
    - git
    - make
    - tar

before_install:
  - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz
  - sudo tar --directory=/usr/local -zxf cmake-3.7.2-Linux-x86_64.tar.gz --strip-components 1

after_success:
  - $CC --version
  - git clone https://bitbucket.org/intelcilkruntime/intel-cilk-runtime.git && cd intel-cilk-runtime
  - libtoolize
  - aclocal
  - automake --add-missing
  - autoconf
  - ./configure
  - make -j2
  - sudo make install -j2
  - cd ..
  - rm -rf intel-cilk-runtime

script:
  - cd tools && git clone https://github.com/wsmoses/Cilk-Clang clang && cd ..
  - mkdir build
  - cd build
  - cmake .. -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_OPTIMIZE_TABLEGEN=1 -DCMAKE_BUILD_TYPE=$BUILD
  - make -j2 clang
  - sudo make install -j2 clang
  - cd ..
  - export CC="clang"
  - export CXX="clang++"
